from django.utils import timezone
# Lengths and values for models

# General
CHAR_GENERAL_MAX_LENGTH = 255
DESCRIPTION_MAX_LENGTH = 500
INT_MIN_VALUE = 1
NUMBER_MIN_VALUE = 1.00

# VehicleType
KM_PER_MAINTENANCE_MIN_VALUE = 2000
KM_PER_MAINTENANCE_MAX_VALUE = 5000
PRICE_MAX_VALUE = 9999

# Vehicle
YEAR_MIN_VALUE = 2010
YEAR_MAX_VALUE = timezone.now().year

# Customer
USER_MAX_LENGTH = 150
USER_MIN_LENGTH = 5
PASSWORD_MIN_LENGTH = 10
PASSWORD_MAX_LENGTH = 100

# Company
COMPANY_ID_MIN_VALUE = 1
COMPANY_ID_MAX_VALUE = 99999999999

# Person
PERSON_ID_MIN_VALUE = 1
PERSON_ID_MAX_VALUE = 99999999999
