# Generated by Django 5.0.6 on 2024-06-09 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('ready_for_use', models.BooleanField(default=True)),
                ('lock_for_rent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('typeOfUses', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=255)),
                ('business_id', models.BigIntegerField(unique=True)),
                ('customer_type', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company')], default='Company', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
                ('person_id', models.BigIntegerField(unique=True)),
                ('customer_type', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company')], default='Person', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customer_id', models.PositiveIntegerField()),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('vehicles', models.ManyToManyField(to='webapp.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.vehicletype'),
        ),
    ]
