# Generated by Django 5.0.6 on 2024-06-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_vehicle_buy_date_alter_vehicle_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 15, 34, 1, 325351)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 15, 34, 1, 325117)),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 15, 34, 1, 324933)),
        ),
    ]
