# Generated by Django 5.0.6 on 2024-06-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rent_start_date_alter_rent_date_alter_rent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='customer_type',
        ),
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 16, 56, 38, 72638)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 16, 56, 38, 72417)),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 16, 56, 38, 72217)),
        ),
    ]
