# Generated by Django 5.0.6 on 2024-06-09 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_company_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='date',
        ),
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 26, 43, 195836)),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 26, 43, 195836)),
        ),
        migrations.AddField(
            model_name='rent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 26, 43, 196969)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 26, 43, 196756)),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 26, 43, 196568)),
        ),
    ]
