# Generated by Django 5.0.6 on 2024-06-09 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_company_created_alter_person_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 31, 38, 317533)),
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 31, 38, 317533)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 31, 38, 318668)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 31, 38, 318450)),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 31, 38, 318251)),
        ),
    ]
