# Generated by Django 5.0.6 on 2024-06-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_company_created_alter_person_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
