# Generated by Django 5.0.6 on 2024-07-03 23:47
from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    # Getting all models (auth and webapp)
    group_model = apps.get_model('auth', 'Group')
    permission_model = apps.get_model('auth', 'Permission')
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    vehicle_type_model = apps.get_model('webapp', 'VehicleType')
    vehicle_model = apps.get_model('webapp', 'Vehicle')
    rent_model = apps.get_model('webapp', 'Rent')
    person_model = apps.get_model('webapp', 'Person')
    company_model = apps.get_model('webapp', 'Company')

    # Group creation. Only Admin and Customer are created
    admin_group, admin_created = group_model.objects.get_or_create(name='Admins')
    customer_group, customer_created = group_model.objects.get_or_create(name='Customers')
    if admin_created and customer_created:
        # Content types for webapp models
        vehicle_type_content_type = content_type_model.objects.get_for_model(vehicle_type_model)
        vehicle_content_type = content_type_model.objects.get_for_model(vehicle_model)
        rent_content_type = content_type_model.objects.get_for_model(rent_model)
        person_content_type = content_type_model.objects.get_for_model(person_model)
        company_content_type = content_type_model.objects.get_for_model(company_model)
        # View permission models for webapp models
        can_view_vehicle_type_permission, created = permission_model.objects.get_or_create(
            codename='view_vehicletype',
            content_type=vehicle_type_content_type
        )
        can_view_vehicle_permission, created = permission_model.objects.get_or_create(
            codename='view_vehicle',
            content_type=vehicle_content_type
        )
        can_view_rent_permission, created = permission_model.objects.get_or_create(
            codename='view_rent',
            content_type=rent_content_type
        )
        can_view_person_permission, created = permission_model.objects.get_or_create(
            codename='view_person',
            content_type=person_content_type
        )
        can_view_company_permission, created = permission_model.objects.get_or_create(
            codename='view_company',
            content_type=company_content_type
        )

        # Creation permission models for webapp models
        can_create_vehicle_type_permission, created = permission_model.objects.get_or_create(
            codename='create_vehicletype',
            content_type=vehicle_type_content_type
        )
        can_create_vehicle_permission, created = permission_model.objects.get_or_create(
            codename='create_vehicle',
            content_type=vehicle_content_type
        )
        can_create_rent_permission, created = permission_model.objects.get_or_create(
            codename='create_rent',
            content_type=rent_content_type
        )
        can_create_person_permission, created = permission_model.objects.get_or_create(
            codename='create_person',
            content_type=person_content_type
        )
        can_create_company_permission, created = permission_model.objects.get_or_create(
            codename='create_company',
            content_type=person_content_type
        )

        # Edit permission model for webapp models
        can_change_vehicle_type_permission, created = permission_model.objects.get_or_create(
            codename='change_vehicletype',
            content_type=vehicle_type_content_type
        )
        can_change_vehicle_permission, created = permission_model.objects.get_or_create(
            codename='change_vehicle',
            content_type=vehicle_content_type
        )
        can_change_person_permission, created = permission_model.objects.get_or_create(
            codename='change_person',
            content_type=person_content_type
        )
        can_change_company_permission, created = permission_model.objects.get_or_create(
            codename='change_company',
            content_type=company_content_type
        )

        # List permission model for webapp models
        can_list_vehicle_type_permission, created = permission_model.objects.get_or_create(
            codename='list_vehicle_type',
            name='Can list vehicle type',
            content_type=vehicle_type_content_type
        )
        can_list_vehicle_permission, created = permission_model.objects.get_or_create(
            codename='list_vehicle',
            name='Can list vehicle',
            content_type=vehicle_content_type
        )
        can_list_person_permission, created = permission_model.objects.get_or_create(
            codename='list_person',
            name='Can list person',
            content_type=person_content_type
        )
        can_list_company_permission, created = permission_model.objects.get_or_create(
            codename='list_company',
            name='Can list company',
            content_type=company_content_type
        )
        can_list_rent_permission, created = permission_model.objects.get_or_create(
            codename='list_rent',
            name='Can list rent',
            content_type=company_content_type
        )
        # Permission assignment for Admin Group
        admin_group.permissions.add(can_view_vehicle_permission)
        admin_group.permissions.add(can_view_vehicle_type_permission)
        admin_group.permissions.add(can_view_rent_permission)
        admin_group.permissions.add(can_view_person_permission)
        admin_group.permissions.add(can_view_company_permission)
        admin_group.permissions.add(can_list_vehicle_permission)
        admin_group.permissions.add(can_list_vehicle_type_permission)
        admin_group.permissions.add(can_list_rent_permission)
        admin_group.permissions.add(can_list_person_permission)
        admin_group.permissions.add(can_list_company_permission)
        admin_group.permissions.add(can_change_vehicle_permission)
        admin_group.permissions.add(can_change_vehicle_type_permission)
        admin_group.permissions.add(can_change_company_permission)
        admin_group.permissions.add(can_change_person_permission)
        admin_group.permissions.add(can_create_vehicle_permission)
        admin_group.permissions.add(can_create_vehicle_type_permission)

        # Permission assignment for Customer Group
        customer_group.permissions.add(can_list_rent_permission)
        customer_group.permissions.add(can_view_rent_permission)
        customer_group.permissions.add(can_create_rent_permission)
        customer_group.permissions.add(can_create_person_permission)
        customer_group.permissions.add(can_create_company_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_vehicletype_price'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]

